# Generated by Django 3.2.8 on 2023-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=254, verbose_name='密码')),
                ('role', models.CharField(choices=[('1', 'Gamer'), ('2', 'Developer')], default='1', max_length=1, verbose_name='角色')),
                ('avatar', models.CharField(max_length=254, verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
