# Generated by Django 4.2 on 2023-11-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=254, verbose_name='密码')),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='电子邮箱')),
                ('role', models.CharField(choices=[('1', 'GAMER'), ('2', 'DEVELOPER')], default='1', max_length=1, verbose_name='角色')),
                ('avatar_index', models.CharField(max_length=2, verbose_name='头像索引')),
                ('gold', models.PositiveIntegerField(default=100, verbose_name='金币')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
