# Generated by Django 4.2 on 2023-08-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_index',
            field=models.CharField(default=5, max_length=2, verbose_name='头像索引'),
            preserve_default=False,
        ),
    ]
