# Generated by Django 4.2 on 2023-11-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='房间名')),
                ('password', models.CharField(blank=True, max_length=8, null=True, verbose_name='房间密码')),
                ('max_member_count', models.SmallIntegerField(default=8, verbose_name='最大人数')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='房主')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='房间成员')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room', verbose_name='房间成员')),
            ],
            options={
                'verbose_name': '房间成员',
                'verbose_name_plural': '房间成员',
                'db_table': 'room_member',
            },
        ),
    ]
